name: CI/CD Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        env:
          VITE_REACT_APP_HOST: ${{ secrets.VITE_REACT_APP_HOST }}
        run: npm run build

      - name: Prepare Deployment Package
        run: |
          mkdir deploy
          cp -r dist server.js package.json package-lock.json deploy/
          cd deploy
          npm install --only=production
          cd ..
          zip -r deploy.zip deploy/*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'bodimate-front'
          environment_name: 'Bodimate-front-env'
          version_label: v_${{ github.run_id }}
          region: 'ap-south-1'
          deployment_package: deploy.zip
